const GET_ALL_USER_INFO_REQUEST = 'users/GET_ALL_USER_INFO_REQUEST'
const GET_ALL_USER_INFO_REQUEST_SUCCESS ='user/GET_ALL_USER_INFO_REQUEST_SUCCESS';

export {
    GET_ALL_USER_INFO_REQUEST,
    GET_ALL_USER_INFO_REQUEST_SUCCESS
}